version: '3.8'

services:
    firebase-custom-token:
        container_name: firebase-custom-token
        image: node:16-alpine3.12
        env_file: .env
        working_dir: /src
        volumes:
            - .:/src
        ports:
            - 8081:8080
        command:
            - /bin/sh
            - -c
            - |
                npm i
                npm run dev